# Generated by Django 5.2.17 on 2026-09-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="criado em"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "plan",
                    models.CharField(
                        choices=[("FREE", "Grátis"), ("PRO", "Pro")],
                        default="FREE",
                        max_length=10,
                        verbose_name="plano",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "provider",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="provedor"
                    ),
                ),
                (
                    "provider_customer_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="id do cliente no provedor",
                    ),
                ),
                (
                    "provider_subscription_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="id da assinatura no provedor",
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fim do período atual"
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "assinatura",
                "verbose_name_plural": "assinaturas",
            },
        ),
    ]
