# Generated by Django 5.2.17 on 2026-09-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="criado em"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Usado na URL pública /b/<slug>",
                        max_length=60,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Sao_Paulo", max_length=64, verbose_name="fuso horário"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="telefone")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="endereço")),
                (
                    "working_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Ex.: {"mon": [["09:00", "18:00"]], "sun": []}',
                        verbose_name="horário de funcionamento",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "salão",
                "verbose_name_plural": "salões",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="criado em"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Proprietário"),
                            ("MANAGER", "Gerente"),
                            ("PROFESSIONAL", "Profissional"),
                        ],
                        default="PROFESSIONAL",
                        max_length=20,
                        verbose_name="papel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "membro",
                "verbose_name_plural": "membros",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "organization"), name="uniq_membership_user_org"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="criado em"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Proprietário"),
                            ("MANAGER", "Gerente"),
                            ("PROFESSIONAL", "Profissional"),
                        ],
                        default="PROFESSIONAL",
                        max_length=20,
                        verbose_name="papel",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False, max_length=64, unique=True, verbose_name="token"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="aceito em"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expira em")),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "convite",
                "verbose_name_plural": "convites",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("accepted_at__isnull", True)),
                        fields=("organization", "email"),
                        name="uniq_active_invitation_per_email",
                    )
                ],
            },
        ),
    ]
